Paginação de Account, Investment, Product e User.
Riko07br/pi-sd-backend pull request #2
Opened 2024-10-16 18:28 UTC by JulioSAlencar

2024-10-16 18:35 UTC, JulioSAlencar commented
Preciso que olhe com atenção o InvestmentResource, Pois utilizei a anotação @RequestParam nele, e como não a usei nos outros, não tenho certeza se está implementado corretamente.

2024-10-16 19:44 UTC, Riko07br requested changes
Deixei os comentários gerais, depois vemos como trocar o pageable que vem no resources por uma classe própria com algumas limitações

2024-10-16 19:44 UTC, Riko07br commented on src/main/java/com/backend/projetointegrador/repositories/AccountRepository.java
> +    Page<Account> findAll(Pageable pageable);
Esse método não vai ser necessário

2024-10-16 19:44 UTC, Riko07br commented on src/main/java/com/backend/projetointegrador/repositories/ProductRepository.java
> +    Page<Product> findAll(Pageable pageable);
Esse método não vai ser necessário

2024-10-16 19:44 UTC, Riko07br commented on src/main/java/com/backend/projetointegrador/resources/InvestmentResource.java
> +            @RequestParam(value = "size", defaultValue = "10") int size,
Isso funciona, mas para manter um padrão pode utilizar o pageable como os demais métodos

2024-10-19 00:50 UTC, Riko07br approved these changes

2024-10-19 00:52 UTC, merged